### ISSUE TITLE
Implement a feed generator for Amazon

### ISSUE THREAD

**Issue by elia** [nebulab/solidus_feeds#8]

**Comment by aldesantis** [comment]
https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf

**Comment by MinasMazar** [comment]
Here I've just gathered a bunch of info and resources about Amazon product feed.

Currently Amazon provides two different integration for Product feeds:

### Marketplace Web Service (MWS) API

Consider Amazon is migrating from MWS to SPI. As mentioned in [**Selling on Amazon Guide**](https://developer.amazonservices.com/)

> the legacy Amazon MWS APIs will be deprecated in the future. We do not yet have an established date, but will let you know and provide both time and tools to support migration of existing Amazon MWS integrations.

Product feeds should be sent on Amazon using XML file format as specified in the [Amazon Marketplace Web Service (Amazon MWS) Documentation](https://docs.developer.amazonservices.com/en_US/feeds/Feeds_SubmitFeed.html). A more detailed guide on how to generate XML is the "[Selling on Amazon ~ Guide to XML](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/XML_Documentation_Intl.pdf)".

In Ruby ecosystem there are some gems providing the integration with MWS but the most significant in my opinion is [Peddler](https://github.com/hakanensari/peddler) which is very popular and well maintained. As its README says:

> Amazon is migrating to the newly-launched Selling Partner API (SP-API). There is no date yet for when MWS APIs will be deprecated. I will add support in Peddler in due course.

### Selling Partner (SPI) API

The [Selling Partner API](https://github.com/amzn/selling-partner-api-docs) is a REST-based API that builds on the functionality of Amazon Marketplace Web Service (Amazon MWS), but provides features to improve usability and security for developers and the seller partners they work with. With the Selling Partner API.

This is the [Developer API Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md) which contains step-by-step informations needed to start a development of an integration for an Amazon seller, while [here's the guide for Amazon vendors](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuideForVendors.md).
Informations about the API can be found on [Selling Partner API Models](https://github.com/amzn/selling-partner-api-models) which contains Swagger models for developers to use to create software to call Selling Partner APIs. The API is really new and AFAIK seems no Ruby clients are present, anyway «_developers can use swagger codegen to generate client libraries from these models_». SPI Api also provides a [sandbox environment](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#the-selling-partner-api-sandbox) to test your application.
One of main features of SPI is the possibility to create **[hybrid applications](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#hybrid-selling-partner-api-applications) that make calls both to the Selling Partner API and to Amazon MWS**. As far as I understood it could be possible to start the development of Amazon MWS and then migrate t SPI.

> Use a hybrid application when your solution requires functionality from both services. When a seller authorizes your hybrid Selling Partner API application, they are (1) authorizing your Amazon MWS developer ID to make calls to Amazon MWS on their behalf, and (2) authorizing the application to make calls to the Selling Partner API on their behalf. If a selling partner has authorized you to make calls to Amazon Marketplace Web Service on their behalf, you can use the Authorization API to migrate that authorization to a hybrid Selling Partner API application. This eliminates the need to request authorization from the selling partner again. For more information, see the Authorization API User Guide.

**Comment by MinasMazar** [comment]
We then decided to not implement this feature on a first round, because of the effort required and higher priority of others. For this reason I close this issue, taking care of removing any reference of Amazon feed from the README.
